### ISSUE TITLE
Icon images

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/taxaprisma#1]
@jhpoelen I found a fungus and had given up on figuring out how to make a comment, so I inserted it in the list; I didn't break anything, did I?

@mariestuder  @KatjaSchulz @mxweber , if anyone prefers a different icon, please shout. Otherwise I'm for going ahead and thinking about it later :)

**Comment by jhpoelen** [comment]
Fungi image looks great . . . thanks for adding it.

**Comment by mariestuder** [comment]
It's great to have Taxaprism!  Thanks, Jorrit.

Jen -- the images are AOK with me.  Thanks for choosing the decorations for the party!
