### ISSUE TITLE
add silhouette for sharks and rays (Elasmobranchii)

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/taxaprisma#3]
as suggested by @mariestuder in https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/issues/14#issuecomment-137581159 .

**Comment by jhammock** [comment]
Good idea! Huh. They're not as distinctive as you'd expect, at least, from other fish. How about this?

http://phylopic.org/assets/images/submissions/993d4e41-51b3-4c59-a4ad-b3dbd482968e.thumb.png

**Comment by mariestuder** [comment]
That phylopic works for me!  Thanks, Jen.

**Comment by jhpoelen** [comment]
thanks for picking a silhouette - i've added it to the taxaprisma list. On http://globalbioticinteractions.org/browse it looks like:

![screen shot 2015-09-08 at 11 12 11 am](https://cloud.githubusercontent.com/assets/1084872/9743346/a9fe6a22-561a-11e5-8fd1-b3e7703e064e.png)

**Comment by mariestuder** [comment]
Looks snazzy!  Thanks for making that update.
